### ISSUE TITLE
Pattern question

### ISSUE THREAD

**Issue by bartq** [LeaVerou/css3patterns#140]
Hi!
Anyone have an idea how to create 45deg (or any degree) rotated tablecloth pattern? :)

Best,
Bartek

**Comment by Pandiora** [comment]
Can you give an example of what you want to achieve?

**Comment by BillyNate** [comment]
@bartq Take the `diagonal stripes` pattern, use the colors from the `tablecloth` pattern to change the `diagonal stripes` to the correct colors (don't forget to set the correct transparency), and finally copy-paste this one stripe to become two stripes and tweak the rotation of the second stripe ;)
Result should be something like
```CSS
{ background-color: white; background-image: repeating-linear-gradient(45deg, rgba(200, 0, 0, 0.5), rgba(200, 0, 0, 0.5) 35px, transparent 35px, transparent 70px), repeating-linear-gradient(135deg, rgba(200, 0, 0, 0.5), rgba(200, 0, 0, 0.5) 35px, transparent 35px, transparent 70px); }
```
